<?php
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui.custom.min.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery.maskedinput-1.2.2.min.js');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/table.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/alert.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/form.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/inicio.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui/jquery-ui.custom.css');

//$this->SwapBytes_Jquery->endLine(true);
?>
<style>
    div.message {
        display:block;
        width:80%;
        margin-top: -0.5%;
        position:absolute;
        top: 15px;
        left:10%;
        border-radius: 5px;
        z-index: 1;
        background: rgba(231,145,0,0.95);
        border: 0.5px solid rgba(102,102,102,0.8);
        box-shadow: 0px 0px 5px #000000;
        -webkit-transition: 300ms all ease;
        -o-transition: 300ms all ease;
        transition: 300ms all ease;
        animation-name: text-anim;
        animation-duration: 10s;
        animation-iteration-count: 1;
        -webkit-animation-name: text-anim;
        -webkit-animation-duration: 10s;
        -webkit-animation-iteration-count: 1;
        -o-animation-name: text-anim;
        -o-animation-duration: 10s;
        -o-animation-iteration-count: 1;
    }
    div.message p {
        color:#FFFFFF;
        padding:15px;
        font-size: 120%;
        font-family: arial,helvetica;
        /*font-family: optima,formata,makimango,ghytsdakx, rockwell;*/
        font-weight: bold;
    }
    div.message2 {
        display:block;
        width:80%;
        position:absolute;
        margin-top: 4%;
        left:10%;
        border-radius: 5px;
        z-index: 1;
        
        background: rgba(133,20,20,0.95);
        border: 0.5px solid rgba(166,34,0,0.8);
        box-shadow: 0px 0px 5px #000000;
        -webkit-transition: 300ms all ease;
        -o-transition: 300ms all ease;
        transition: 300ms all ease;
        animation-name: text-animb;
        animation-duration: 13s;
        animation-iteration-count: 1;
        -webkit-animation-name: text-animb;
        -webkit-animation-duration: 13s;
        -webkit-animation-iteration-count: 1;
        -o-animation-name: text-animb;
        -o-animation-duration: 13s;
        -o-animation-iteration-count: 1;
    }
    div.message2 p {
        color:#FFFFFF;
        padding:15px;
        font-size: 120%;
        text-align: center;
        font-family: arial,helvetica;
        /*font-family: optima,formata,makimango,ghytsdakx, rockwell;*/
        font-weight: bold;
    }
    @keyframes text-anim {
        0% {top: 5px;opacity: 0;}
        10% {top: 15px;opacity: 1;}
        25% {top: 15px;opacity: 1;}
        50% {top: 15px;opacity: 1;}
        75% {top: 15px;opacity: 1;}
        87,5% {top: 15px;opacity: 0.5;}
        100% {top: 75px;opacity: 0;}
    }
    @-webkit-keyframes text-anim {
        0% {top: 5px;opacity: 0;}
        10% {top: 15px;opacity: 1;}
        25% {top: 15px;opacity: 1;}
        50% {top: 15px;opacity: 1;}
        75% {top: 15px;opacity: 1;}
        87,5% {top: 15px;opacity: 0.5;}
        100% {top: 75px;opacity: 0;}
    }
    @keyframes text-animb {
        0% {top: -300px;opacity: 0;}
        10% {top: 15px;opacity: 1;}
        25% {top: 15px;opacity: 1;}
        50% {top: 15px;opacity: 1;}
        75% {top: 15px;opacity: 1;}
        87,5% {top: 15px;opacity: 0.5;}
        100% {top: 75px;opacity: 0;}
    }
    @-webkit-keyframes text-animb {
        0% {top: -300px;opacity: 0;}
        15% {top: 15px;opacity: 1;}
        25% {top: 15px;opacity: 1;}
        50% {top: 15px;opacity: 1;}
        75% {top: 15px;opacity: 1;}
        87,5% {top: 15px;opacity: 0.5;}
        100% {top: 75px;opacity: 0;}
    }
    #nomtut{
        font-size: 10px;
        text-transform: uppercase;
    }
    .lblInfoContact {
     background-color: #0066FF;
    border: 1px solid #0000CC;
    color: #FFFFFF;
    font-family: Arial,Helvetica,sans-serif;
    font-size: 14px;
    
    padding-bottom: 2px;
    text-align: center;
    width: 100%;
}

.lblInfoContact h3{
    font-size: 14px;
    font-weight: bold;
    padding-top: 0px;
    padding-bottom: 0px;
    margin-top: 4px;
    margin-bottom: 4px;
}
</style>
<!--<div class="lblInfoContact"><b>Soporte Técnico para Reinscripciones Online</b> Durante el proceso de 8:30am a 6pm<br> Teléfonos: +58(416)408.42.94 y +58(424)250.38.56</div>-->
<h2><?php echo $this->escape($this->title); ?></h2>
<br>
<?php echo $this->message; ?>
<?php echo $this->message2; ?>
<table border="0" cellpadding="0" cellspacing="0" width="1000px" style="padding: 0 0 0 10; margin-left:auto; margin-right:auto;">
    <tr>
        <td id="left" width="30%" valign="top"> <!-- Prefil -->
            
           <div id="izq" class="ui-widget-content ui-corner-all">
                <h3 class="ui-widget-header-une ui-corner-all" style="z-index:-1000;">Perfil</h3>
<!--               rgba(0, 0, 255, 1)-->
                <img class="perf" src= <?php echo $this->baseUrl() . '/images/profilepic.php' . ' alt=' . $this->baseUrl() . '/images/empty_profile.jpg' ?> style="-moz-box-shadow: 0 0 10px black;"/>
                <p class="ui-corner-all subTitbg-y">
                <span style="position:relative;">
                <span class="subTit-y">Datos Personales:</span>
                </span>
                </p>
                <p class="perfcont">
                    <span class="ui-corner-all ui-icon ui-icon-person perficon"></span>
                        <?php echo $this->usr[0]["nombre"]; ?>
                </p>
                <p class="perfcont">
                    <span class="ui-corner-all ui-icon ui-icon-mail-closed perficon"></span>
                        <?php  echo $this->usr[0]["correo"]; ?>
                </p>
                <p class="perfcont">
                    <span class="ui-corner-all ui-icon ui-icon-calendar perficon"></span>
                        <?php echo $this->usr[0]["nacimiento"]; ?>
                </p>
                <p class="perfcont">
                    <span class="ui-corner-all ui-icon-new ui-icon-new-telefono perficon"></span>
                        <?php echo $this->usr[0]["tlf"]; ?>
                </p>
                <p class="perfcont">
                    <span class="ui-corner-all ui-icon-new ui-icon-new-celular perficon"></span>
                        <?php echo $this->usr[0]["cel"]; ?>
                </p>
                <p class="perfcont">
                    <span style="float:left; height:32px;">
                        <span class="ui-corner-all ui-icon ui-icon-home perficon"></span>

                    </span>
                        <?php echo $this->usr[0]["dir"]; ?>
               </p>
                <div id="datosacademicos">
                    
                    <?php echo $this->pasantias; ?>
   
                </div>
                <div id="comunitario">
                    
                    <?php  echo $this->servComun; ?>
                </div>
                <div id="pasantias">
                    
                    <?php  echo $this->setPasantias; ?>
                </div>
                <div id="datostesis">
                    
                    <?php 
                        echo $this->tesistas; 
                        
                    ?>
                </div>
                <div id="datostutor">
                    
                    <?php  echo $this->tutores; ?>
                </div>
            </div>
        </td> <!-- Fin Prefil -->
        
        <td id="rights" width="70%" valign="top"> <!-- horario y actividades -->

            <div id="horario" class="ui-widget-content ui-corner-all movible content">
            <div class="relative" style="position:relative">
                <h3 class='ui-widget-header-une ui-corner-all'>Horario</h3>
                <span class="leyenda clases">Horario de estudiante</span>
                <span class="leyenda profesor">Horario de Profesor</span>
                <a class="botondescargar" onclick="printFunction()">Descargar</a>
            </div>
               <div id="content2" class='widget-contenido print'>
                  <?php echo $this->horario; ?>

               </div>
            </div>
            <div id="calendario" class="ui-widget-content ui-corner-all movible content">
               <h3 class='ui-widget-header-une ui-corner-all' style='z-index:-1000;'>Calendario de actividades</h3>
                  <div id="content" class='widget-contenido'>
                    <?php 
                   
                        echo $this->actividades;
                        echo $this->Descargables;
                        echo $this->cuotas;
                        echo $this->feriados;
                        echo $this->documentos;
                        echo $this->estacionamiento;
                       
                    ?>
                  </div>
            </div>

         

        </td> <!-- Fin horario y actividades -->
    </tr>
    <tr>
    </tr>
</table>
<br>
<div id="tableData" align="center"></div>
<?php echo $this->SwapBytes_Crud_Form->getHtml(); ?>
<script type='text/javascript'>
    $(document).ready(function(){
        <?php
            echo $this->SwapBytes_Jquery->getLoading('loading');
            echo $this->SwapBytes_Ajax->getUrlAjaxJS();
            $function = "window.location.href = urlAjax + 'descargar/'";
            echo $this->SwapBytes_Jquery->setClick('btnDescargar', $function);  
            //echo $this->SwapBytes_Crud_Form->getJavaScript();
            //echo $this->SwapBytes_Crud_Action->getJavaScript('tableData');
            //echo $this->filters->getJavaScript('tableData');
        ?>
    });
    
    $('.click').hover(function(){
        $(this).css('cursor','pointer');
        },
        function(){
        $(this).css('cursor','default');
    }); 
    
    $('.click').click(function(){
        
        var id = $(this).attr('id');
        
        window.location.href = urlAjax + 'descargargables/id/'+id;
        
    });
    printFunctionCSS = new String('<style>table tr td,table tr th{border: 1.5px solid black;}.profesor{border: 3px solid black;}</style>')
    function printFunction() {
        center = (window.outerWidth) / 2 - 400;
        console.log(center);
        var newWindow = window.open("","Descargar mi Horario", "width=800, height=800, left=" +center);
        newWindow.document.write(printFunctionCSS + document.getElementById("content2").innerHTML);
        newWindow.print();
        
    }
    setTimeout(function(){
        $("#msg").hide();
    },10000);

    setTimeout(function(){
        $("#msg2").hide();
    },13000);
   // function imprimir(){

      //  window.location.href = "urlAjax + 'descargar/";
        //window.open(urlAjax + "descargar/");
    //}
</script>
