<?php
/*<script type="text/javascript" src="../lib/jquery.js"></script>
<script type='text/javascript' src='../lib/jquery.bgiframe.min.js'></script>
<script type='text/javascript' src='../lib/jquery.ajaxQueue.js'></script>
<script type='text/javascript' src='../lib/thickbox-compressed.js'></script>
<script type='text/javascript' src='../jquery.autocomplete.js'></script>
<script type='text/javascript' src='localdata.js'></script>*/

$this->headScript()->appendFile($this->baseUrl() . '/js/jquery-1.4.4.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery-autocomplete/demo/localdata.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery-autocomplete/lib/jquery.bgiframe.min.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery-autocomplete/lib/jquery.ajaxQueue.js');
//$this->headScript()->appendFile($this->baseUrl() . '/js/jquery-autocomplete/lib/thickbox-compressed.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery-autocomplete/jquery.autocomplete.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui-1.8.14.custom.min.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery.maskedinput-1.2.2.min.js');

$this->headLink()->appendStylesheet($this->baseUrl() . '/css/table.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/alert.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/form.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/pagination.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui/jquery-ui.custom.css');

?>
<meta charset="utf-8">
<h2><?php echo $this->escape($this->title); ?></h2>
<br>
<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px 0px 0px 10px; margin-left:auto; margin-right:auto;">

    <tr>
        <td align="center">
            <?php include_once('filtros.phtml'); ?>
        </td>
    </tr>
    <tr>
        <td align="center"><p id="mensaje" style="display: none" ></p></td>
    </tr>
    <tr>
        <td>
            <div id="tableData">&nbsp;</div>
        </td>
    </tr>
</table>


<?php echo $this->SwapBytes_Crud_Form->getHtml(); ?> 

<script type='text/javascript'>
    $(document).ready(function(){
     

         $('#btnList').click(function(){
         $buscar = $('#txtBuscar').val();
          for ($i = 0 ; $i<50 ; $i++){
               $buscar = $buscar.replace('/','~');
          }
         $('#txtBuscar').val($buscar);
        })

<?php
    echo $this->SwapBytes_Jquery->getLoading('loading');
    echo $this->SwapBytes_Ajax->getUrlAjaxJS();
    echo $this->SwapBytes_Crud_Form->getJavaScript();
    echo $this->SwapBytes_Crud_Action->getJavaScript('tableData');
    echo $this->filters->getJavaScript('tableData');
    
?>
        
         $('#btnList').click(function(){
         $rempl = $('#txtBuscar').val();
          for ($i = 0 ; $i<50 ; $i++){
               $rempl = $rempl.replace('~','/');
          }
         $('#txtBuscar').val($rempl);
        });


      $.getJSON(urlAjax + "filter", function(data){executeCmdsFromJSON(data)});  
       $('#filtro').change(function(){
       $.getJSON(urlAjax + "list/filtro/"+$('#Sede').val(), function(data){executeCmdsFromJSON(data)});
       
       });
    });
    
    
    
       
    
    
</script>