<?php
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/table.css');
?>
<h2><?php echo $this->escape($this->title); ?></h2>
<br>
<table width="100%" cellpadding="0" border="0" align="center">
    <tr>
        <td width="100%" height="30" style="text-align:center">
            C.I. del Alumno:&nbsp;
            <input autocomplete="off" type="text" id="txtCI" size="14" maxlength="8" />
            <input type="submit" id="btnGenerate" value="Buscar"/>
        </td>
    </tr>
    <tr>
        <td align="center"><div id="tblLista"></div></td>
    </tr>
</table>
<script type='text/javascript'>
    $(document).ready(function(){
        $("#loading").ajaxStart(function(){$(this).show();});
        $("#loading").ajaxStop(function(){$(this).hide();});

        urlAjax = "<?php echo $this->baseUrl() . '/' . $this->module . '/' . $this->controller . '/' ?>";

        $('#btnGenerate').click(function(){$.getJSON(urlAjax + "generar/ci/"+$("#txtCI").val(), function(data){executeCmdsFromJSON(data)});});
    });
</script>
