<?php
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/table.css');
?>
<h2><?php echo $this->escape($this->title); ?></h2>
<br>
<table border="0" cellpadding="0" cellspacing="0" width="900px" style="padding: 0 0 0 10; margin-left:auto; margin-right:auto;">
    <tr>
        <td align="center">
            <table border="0" cellpadding="0" cellspacing="0" width="140px">
                <tr>
                    <td align="right" style="font-weight:bolder;" width="20" rowspan="2">CI:</td>
                    <td align="center" style="font-weight:bolder;" width="60" rowspan="2">
                        <input autocomplete="off" type="text" id="txtCI" size="14" maxlength="8" />
                    </td>
                    <td align="center" style="font-weight:bolder;" width="60" rowspan="2">
                        <button type="button" id="btnGenerar">Generar</button>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
<script type='text/javascript'>
    $(document).ready(function(){
        $("#loading").ajaxStart(function(){$(this).show();});
        $("#loading").ajaxStop(function(){$(this).hide();});

        urlAjax = "<?php echo $this->baseUrl() . '/' . $this->module . '/' . $this->controller . '/' ?>";

        $('#btnGenerar').click(function(){
            window.location.href = urlAjax + "descargar/ci/" + $("#txtCI").val();
        });
    });
</script>
