
<?php
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui.custom.min.js');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/table.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui/jquery-ui.custom.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/alert.css');
?>
<h2><?php echo $this->escape($this->title); ?></h2>
<br>
<table border="0" cellpadding="0" cellspacing="0" width="900px" style="padding: 0 0 0 10; margin-left:auto; margin-right:auto;">
    <tr>
        <td>
            <div align="center">
               <h1 class="titulo"> Lista de periodos </h1>
            </div>
        </td>
    </tr>
</table>
<style type="text/css">
.titulo{
    font-size: 16px;
    font-weight: bold;
    margin-bottom: 15px;
}
.tableData{
    margin: 0% auto;
}
</style>
