<?php

$this->headScript()->appendFile($this->baseUrl() . '/js/jquery.maskedinput-1.2.2.min.js');

$this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui.custom.min.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery.md5.js');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/table.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/alert.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/form.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/pagination.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui/jquery-ui.custom.css');


//$this->SwapBytes_Jquery->endLine(true);
?>
<meta charset="utf-8">
<h2><?php echo $this->escape($this->title); ?></h2>
<br>
<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px 0px 0px 10px; margin-left:auto; margin-right:auto;">
    <tr>
        <td align="center">

            <?php include_once('filtros.phtml'); ?> 
        </td>
    </tr>
    <tr>
        <td>
            <div id="tableData">&nbsp;</div>
        </td>
    </tr>
</table>

<?php echo $this->SwapBytes_Crud_Form->getHtml(); ?>

<script type='text/javascript'>
    var globalCount = 1;
    $(document).ready(function(){
        MyurlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;
        
        <?php
            echo $this->SwapBytes_Jquery->getLoading('loading');
            echo $this->SwapBytes_Ajax->getUrlAjaxJS();
            echo $this->SwapBytes_Crud_Form->getJavaScript();
            echo $this->SwapBytes_Crud_Action->getJavaScript('tableData');
            echo $this->filters->getJavaScript('tableData', $this->SwapBytes_Jquery_Ui_Form->buttonDisable('btnAdd', true));
            echo $this->SwapBytes_Jquery->fillSelect('selEstado', 'estado');
            $function = $this->SwapBytes_Jquery->getJSON('cambiar', null, array('data' => $this->SwapBytes_Jquery->serializeForm()));
        ?>

        $.getJSON(urlAjax + "filter", function(data){executeCmdsFromJSON(data)});
        
        
   
    });
    function asignar(cod){
        MyurlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;
        $.getJSON(MyurlAjax + '/addoreditload/cod/'+cod+'/Periodo/'+$('#Periodo').val()+'/Sede/'+$('#Sede').val(),function(data){executeCmdsFromJSON(data)});
    }
    function add_e(cod){
        MyurlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;
        cod = (cod) ? cod : '';

        var id = '#evaluadores' + cod;
        
        
        
        var count = $('.evaluadores').size();
        globalCount = cod + 1;

        $.getJSON(MyurlAjax + '/evaluador/Periodo/'+$('#Periodo').val()+'/Sede/'+$('#Sede').val()+'/count/'+count,function(data){executeCmdsFromJSON(data)});

    }

    function del_e(cod){
        MyurlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;
        cod = (cod) ? cod : '';
        
        
        var id = '#evaluadores' + cod;
        
        
        var count = $('.evaluadores').size();
        globalCount = cod -1;
        
        $.getJSON(MyurlAjax + '/evaluadordelete/count/'+count,function(data){executeCmdsFromJSON(data)});
    }
    

    $("#btnGuardar").live("click", function(e){
        var globalCount = $('.evaluadores').size() - 1;

        var evaluadores = 'row=' + $('#evaluadores').val()+'-'+ $('#rol_eval').val();

        console.log(e);

        for(i=1;i<=globalCount;i++){
            
            var id = '#evaluadores' + i;
            var rol = '#rol_eval' + i;
            evaluadores += '&row=' +$(id).val()+'-'+$(rol).val();
        }
        
        
        $.getJSON(MyurlAjax + "/addoreditconfirm/", 
        {
         cod: $("#cod").val(),
         periodo: $("#Periodo").val(),
         evaluadores: evaluadores
        },function(data){executeCmdsFromJSON(data)});
    });

</script>