<?php
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui.custom.min.js');
//$this->headScript()->appendFile($this->baseUrl() . '/js/jquery.maskedinput-1.2.2.min.js');

$this->headLink()->appendStylesheet($this->baseUrl() . '/css/alert.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/form.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/pagination.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/table.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui/jquery-ui.custom.css');
?>
<h2><?php echo $this->escape($this->title); ?></h2>
<table border="0" cellpadding="0" cellspacing="0" width="830px" style="padding: 0 0 0 10; margin-left:auto; margin-right:auto;">
    <tr>
        <td align="center">
            <?php include_once('filtros.phtml'); ?>
        </td>
    </tr>
</table>
<br>
<div id="tableData" align="center"></div>
<?php echo $this->SwapBytes_Crud_Form->getHtml(); ?>
<script type='text/javascript'>
$(document).ready(function(){
<?php
    echo $this->SwapBytes_Jquery->getLoading('loading');
    echo $this->SwapBytes_Ajax->getUrlAjaxJS();
    echo $this->SwapBytes_Crud_Form->getJavaScript();
    echo $this->SwapBytes_Crud_Action->getJavaScript('tableData');
	echo $this->filters->getJavaScript('tableData');
	echo $this->SwapBytes_Jquery->fillSelect('selEstado', 'estado');
//	$function = $this->SwapBytes_Jquery->getJSON('cambiar', null, array('data' => $this->SwapBytes_Jquery->serializeForm(), 'filters', "escape($('#tblFiltros').find(':input').serialize())"));
//	echo $this->SwapBytes_Jquery->setChange('selEstado', $function);
?>
$('#selEstado').change(function () {
    $.getJSON(urlAjax + "cambiar/data/" + escape($(':input').serialize()) + "/filters/" + escape($('#tblFiltros').find(':input').serialize()) + "", function (d) {
        executeCmdsFromJSON(d)
    });
});
   $.getJSON(urlAjax + "filter", function(data){executeCmdsFromJSON(data)});
	$("#selEstado option:eq(0)").before("<option value='0'>Estado</option>");
	$("#selEstado option:first").css('text-align:center;font-weight:bolder;');
	$("#selEstado option:first").attr('selected','selected');
   $('#btnRetirar_Semestre').live( 'click', function(){
      $.getJSON(urlAjax + "loadretirarsemestre/buscar/" + encodeURIComponent($('#btnRetirar_Semestre').val()) + "/filters/" + escape($('#tblFiltros').find(':input').serialize()) + "", function (d) {
            executeCmdsFromJSON(d)
      });
   } );
});
</script>
