<?php
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui.custom.min.js');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/table.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui/jquery-ui.custom.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/alert.css');
?>
<h2><?php echo $this->escape($this->title); ?></h2>
<br>

<table border="0" cellpadding="0" cellspacing="0" width="900px" style="padding: 0 0 0 10; margin-left:auto; margin-right:auto;">
    <tr>
        <td align="center" colspan="2">
            <?php include_once('filtros.phtml'); ?>
        </td>
        
    </tr>
    <tr>
    	<td>
        <div id="tblSolicitudes"></div>
       </td>
    </tr>
</table>



<?php echo $this->SwapBytes_Crud_Form->getHtml(); //<!-- Declaracion del form-->?> 
<script type='text/javascript'>
$(document).ready(function(){
<?php

    echo $this->SwapBytes_Jquery->getLoading('loading');
    echo $this->SwapBytes_Ajax->getUrlAjaxJS();
    echo $this->SwapBytes_Crud_Action->getJavaScript('tblSolicitudes');//javasripct de los filtros
    echo $this->SwapBytes_Crud_Form->getJavaScript(); //javascripct de los modal
    echo $this->filters->getJavaScript('tblSolicitudes');//, "$('#btnDescargar').attr('disabled', true);$('#rdbFormatXLS').attr('disabled', true);$('#rdbFormatPDF').attr('disabled', true);");
    
?>
});

function estado(id){
    $.getJSON(urlAjax+"estado/id/"+ id, function(data){
        executeCmdsFromJSON(data);
        $('#btnList').click();
    });
} 

</script>

