<?php
    $this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui.custom.min.js');
    $this->headScript()->appendFile($this->baseUrl() . '/js/jquery.maskedinput-1.2.2.min.js');
    $this->headScript()->appendFile($this->baseUrl() . '/js/sweetalert/sweetalert.min.js');
    $this->headScript()->appendFile($this->baseUrl() . '/js/validator.js');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/alert.css');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/validator.css');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui/jquery-ui.css');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui/jquery-ui.custom.css');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/js/sweetalert/sweetalert.css');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/form.css');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/table.css');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/alert.css');
?>
<style>
    .title {
        font-size: 20px;
        color: #000;
        margin: 10px auto;
        text-align: center;
    }
    .alert {
        display: block;
        width: 100%;
    } 
    .error {
        display: none;
        margin-left: 10px;
    }          
    .error_show{
        color: red;
        margin-left: 10px;
    }
    div.ui-dialog{
        top: 50%;
        left: 37%;
    }
    #registro_vacante {
        width: 720px;
    }
    #registro_vacante dl dd {
        margin: 2.5px 0px;
    }
    #registro_vacante dl dd input[type="text"]{
        padding: 2.5px;
        padding-left: 5px;
        margin-top: -5px;
        display: inline-block;
    }
    .valid {
        content: url(http://omicron.une.edu.ve/MiUNE2/images/icons/tick.png);
    }
    .invalid {
        content: url(http://omicron.une.edu.ve/MiUNE2/images/icons/cross.png);
    }
    #empresa_id, #fk_contrato{
        margin-top: -25px;
    }
    #checkbox_direccion, #sexo {
        margin-top: -15px;
    }
    textarea {
        width: 435px;
        max-width: 435px;
        min-width: 435px;
        height: 50px;
        min-height: 50px;
    }
    #checkVacante {
        display: block;
        padding: 10px;
        margin: 15px auto;
        transition: 300ms all ease;
    } 
    #checkVacante:hover {
        box-shadow: 0.3px 0.3px 0.4px #666;
    }
    .tick, .cross {
        display: inline-block;
        text-align: left;
        margin-left: 270px;
        margin-top: 30px;
        position: absolute;
    }
    div.ui-dialog{
        top: 50%;
        left: 37%;
    }
</style> 
<h2> <?php echo $this->escape($this->title); ?></h2>
<table border="0" cellpadding="0" cellspacing="0" width="500px" style="padding: 0 0 0 10; margin-left:auto; margin-right:auto;">
    <tr>
        <td>
            <h2 class="title">Registre una Vacante</h2>
            <div class="alert"> Para registrar una nueva Vacante no se debe dejar ningun espacio en blanco y los campos en rojo son incorrectos Por favor verificar.</div>
        </td>
    </tr>
    <tr>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td align="center"> 
        <?php
            $this->form->setAction($this->url(). '/');
            echo $this->form;
        ?>
            <img class="tick" src="/MiUNE2/images/icons/tick.png" alt="Aceptado"> <img class="cross" src="/MiUNE2/images/icons/cross.png" alt="Negado">
        </td>
    </tr>
</table>
<?php echo $this->SwapBytes_Crud_Form->getHtml(); ?>
<script type="text/javascript">
    $(document).ready(function(){
        <?php
            echo $this->SwapBytes_Ajax->getUrlAjaxJS();
            echo $this->SwapBytes_Crud_Form->getJavaScript();       
            echo $this->SwapBytes_Jquery->getLoading('loading'); 
        ?>
        $(".tick").hide();
        $(".cross").hide();
        //Definimos Validaciones para los Inputs
        var objectToValidations =   [   
                                        {input: "title",       type: "alpha-numeric", fn: function(){}},
                                        {input: "vacantes",    type: "numeric",       fn: function(){}},
                                        {input: "edad",        type: "numeric",       fn: function(){}},
                                        {input: "descripcion", type: "empty",         fn: function(){}},
                                        {input: "requisitos",  type: "empty",         fn: function(){}},
                                        {input: "beneficios",  type: "empty",         fn: function(){}},
                                        {input: "direccion",   type: "empty",         fn: function(){}}
                                    ];
        //AJAX Consulta RIF
        $("body").delegate("#checkbox_direccion","change",function(){
            if($("#checkbox_direccion").is(':checked')){
                var variable = $("#empresa_id").val();
                $.ajax({
                    url: urlAjax + "getAddress",
                    data: {"empresa": variable},
                    dataType: "json",
                    async: true,
                    success: function(data) {
                        if(data[0]){
                            $("#direccion").val(data[1]);
                        }
                    },
                });
            }
        });
        //Submit
        $("#checkVacante").click(function(e){
            e.preventDefault();
            $.ajax({
                url: urlAjax + "addVacante/",
                data: {
                    "empresa":          $("#empresa_id").val(),
                    "title":            $("#title").val(),
                    "contrato":         $("#fk_contrato").val(),
                    "vacantes":         $("#vacantes").val(),
                    "edad":             $("#edad").val(),
                    "sexo":             $("input[name=sexo]:checked").val(),
                    "descripcion":      $("#descripcion").val(),
                    "requisitos":       $("#requisitos").val(),
                    "beneficios":       $("#beneficios").val(),
                    "direccion":        $("#direccion").val(),
                    "fechaculminacion": $("#fechaculminacion").val(),
                },
                dataType: "json",
                async: true,
                success: function(data) { executeCmdsFromJSON(data); },
            });
        });
        //llamamos al validator 
        validator.insertValidation(objectToValidations);
        <?php 
            echo $this->SwapBytes_Jquery_Mask->singelNumber("vacantes") . ";";
            echo $this->SwapBytes_Jquery_Mask->age("edad") . ";";
        ?>
        var timer   = new Date();
        $("#fechaculminacion").datepicker({changeYear: true, changeMonth: true, dateFormat: 'yy-mm-dd'}).datepicker("setDate", new Date(timer.getFullYear(),timer.getMonth() + 1,timer.getDate()));
    });
</script>