<?php
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery.maskedinput-1.2.2.min.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui.custom.min.js');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/transactions.misgrupos.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/table.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/alert.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/form.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui/jquery-ui.custom.css')
//$this->SwapBytes_Jquery->endLine(true);
?>
<h2><?php echo $this->escape($this->title); ?></h2>

<!--<div id="busqueda">
    <table id="tblbusqueda"  align="center">
            <tr>
                <td>
                    <p id="cedula">Cédula</p>
                </td>
                <td>
                    <input id="cedulatxt" type="text" >
                </td>
                <td>
                    <input id="verclik" type="button" value="ver" >
                </td>
            </tr>
    </table>  
</div>-->

<br>

<table>
        <div id="fotoDiv" align="center"><input id="foto" width="120" type="image" height="161" disabled="disabled" alt="Foto:" name="foto" style="-moz-box-shadow: 0 0 10px black;"></div>
        <br>
        <tr>
            <div id="datosusuario" align="center" ></div>
        </tr>
        <br>
        <tr>
        
            <div align="center">
               
                <button type="button"  id="generarsolicitud" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button" aria-disabled="false"><span class="ui-button-text">Generar Solicitud</span></button>
                 <button type="button"  id="imprimir" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button" aria-disabled="false"><span class="ui-button-text">Imprimir</span></button>    
                
             
                
                
            </div>
            <br>
            <div id="botones" align="center"></div>
        </tr>
</table> 

<br>
<br>

<table>
        <tr>
            <div id="tblcuadrado" align="center" style=" "border="0" cellpadding="0" cellspacing="0" class="list"></div>
        </tr>
        <br>
        <tr>
            <div id="leyenda" align="center" style=" "border="0" cellpadding="0" cellspacing="0" class="list"></div>
        </tr>
</table> 

<script type='text/javascript'>
    $(document).ready(function(){
        $("#loading").ajaxStart(function(){$(this).show();});
        $("#loading").ajaxStop(function(){$(this).hide();});  
        $('#fotoDiv').hide();
        $('#generarsolicitud').hide();
        $('#imprimir').hide();
        
        $(window).load(function(){
            $.getJSON(urlAjax + "verificar", function(data){executeCmdsFromJSON(data)});
        });
        
        <?php
            echo $this->SwapBytes_Ajax->getUrlAjaxJS();
//            echo $this->SwapBytes_Jquery->getLoading('loading');
        ?> 
//        <?php
//            echo $this->SwapBytes_Crud_Form->getJavaScript();
//            $function = "window.location.href = urlAjax + 'descargar/data/' + $(':input').serialize();";
//
//            echo $this->SwapBytes_Jquery->setClick('imprimir', $function);
        ?>//    
        
//        $('#verclik').click(function(){
//             $.getJSON(urlAjax + "verificar/ci/"+$("#cedulatxt").val(), function(data){executeCmdsFromJSON(data)});
//        });
        
        $('#generarsolicitud').click(function(){
            $.getJSON(urlAjax + "generarsolicitud/ci/"+$("#cedulatxt").val(), function(data){
                executeCmdsFromJSON(data);
                $('#generarsolicitud').hide();
                $('#imprimir').show();
            });
        });
        
        $('#imprimir').click(function(){
            window.location.href = urlAjax + 'descargar/ci/'+$("#cedulatxt").val();
        });
        
        
    });
</script>
