<?php
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui.custom.min.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery.maskedinput-1.2.2.min.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery.showLoading.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery.showLoading.min.js');

$this->headLink()->appendStylesheet($this->baseUrl() . '/css/showLoading.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/table.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/alert.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/form.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui/jquery-ui.custom.css');

//$this->SwapBytes_Jquery->endLine(true);
?>
<h2><?php echo $this->escape($this->title); ?></h2>
<br>
<table border="0" cellpadding="0" cellspacing="0" width="1000px" style="padding: 0 0 0 10; margin-left:auto; margin-right:auto;">
    <tr>
        <td align="center">
            <?php include_once('filtros.phtml'); ?>
        </td>
        <td>
            <div id="puestoscant"></div>

        </td>
    </tr>
    <tr>
        <td colspan="2">
            <div id="under"></div>
        </td>
    </tr>
</table>
<br>
<div id="tableDatasec" align="center"></div><br><br>
<div id="tableData" align="center"></div>
<div id="undertable" style="font-size: 16px;"></div>
<?php echo $this->SwapBytes_Crud_Form->getHtml(); ?>
<script type='text/javascript'>
    $(document).ready(function(){
<?php
    echo $this->SwapBytes_Jquery->getLoading('loading');
    echo $this->SwapBytes_Ajax->getUrlAjaxJS();
    echo $this->SwapBytes_Crud_Form->getJavaScript();
    echo $this->SwapBytes_Crud_Action->getJavaScript('tableData');
    echo $this->filters->getJavaScript('tableData');
    echo $this->trigger;
    

?>
    

    $('#btnAsignar').click(function (){
           $.getJSON(urlAjax + "asignar/data/" + escape($('#tableData').children().children().children().find('td').children(':checked').serialize()) + '/filter/' + escape($('#tblFiltros :input').serialize()), function(data){
               executeCmdsFromJSON(data);
           
           $('#frmModal').parent().find("button:contains('Continuar')").click(function(){
                 jQuery('#frmModal').parent().showLoading(
                                {
                                'addClass': 'loading-indicator'
                                }
                                );
            });

            

})
        });


    
    
            $.getJSON(urlAjax + "filter", function(data){executeCmdsFromJSON(data)});

            
    });




  function changepass(){

      $.getJSON(urlAjax + "changepass", function(data){executeCmdsFromJSON(data)});
  }

  function listado(){
      window.location.href = urlAjax + "imprimir/pk/" + id;
  }

  
</script>