<?php
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery.maskedinput-1.2.2.min.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui.custom.min.js');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/alert.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/form.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/pagination.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/table.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui/jquery-ui.custom.css');
?>
<style type="text/css">
.selDate{
    display: inline-block;
    position: relative;
    margin: 0px 0px 0px 267px;
    top: -46px;
}
.selDateDesde{
    width: 85px;
    height: 25px;
    font-weight: bold;
    padding: 2.5px;
    vertical-align: center;
}

.selDateHasta{
    width: 85px;
    height: 25px;
    font-weight: bold;
    padding: 2.5px;
    vertical-align: center;
    margin: 0px 0px 0px 0px;
}
.ajuste{
    margin: 0px 0px 0px 10px;
}
table.tableData tr:last-child td:last-child{

background-color: yellow;

}
tr.Error{
    background-color: rgba(255,0,0,0.5);
}
tr.Error:hover{
    background-color: rgba(255,0,0,0.5);
}


</style>
<h2><?php echo $this->escape($this->title); ?></h2>
<br>
<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px 0px 0px 10px; margin-left:auto; margin-right:auto;">
    <tr>
        <td align="center">
            <?php include_once('filtros.phtml'); ?>
            <div class="selDate" id="selDate">
               <label>Desde: </label> <input type="text" class="selDateDesde" name="selDateDesde"  placeholder="Fecha Desde" id="selDateDesde">
                <label class="ajuste">Hasta: </label> <input type="text" class="selDateHasta" name="selDateHasta" placeholder="Fecha Hasta" id="selDateHasta">
            </div>
        </td>
    </tr>
    <tr>
        <td>
            <div id="tableData">&nbsp;</div>
        </td>
    </tr>
</table>
<?php echo $this->SwapBytes_Crud_Form->getHtml(); ?>
<script type='text/javascript'>
    
      $(function() {
        $( "#selDateDesde" ).datepicker({dateFormat: 'yy-mm-dd'}).datepicker("setDate", new Date());
        $( "#selDateHasta" ).datepicker({ dateFormat: 'yy-mm-dd'}).datepicker("setDate", new Date());
      });
    $(document).ready(function(){
        <?php
            echo $this->SwapBytes_Jquery->getLoading('loading');
            echo $this->SwapBytes_Ajax->getUrlAjaxJS();
        	echo $this->SwapBytes_Crud_Form->getJavaScript();
            echo $this->SwapBytes_Crud_Action->getJavaScript('tableData');
        	echo $this->filters->getJavaScript('tableData');
        ?> 

        $.getJSON(urlAjax + "filter", function(data){executeCmdsFromJSON(data)});
        function list(){
            $.getJSON(urlAjax + "list/filters/"+escape($('#tblFiltros').find(':input').serialize()), { selDateDesde : $("#selDateDesde").val(), selDateHasta : $("#selDateHasta").val() }, function(d){executeCmdsFromJSON(d)});
        }

        $("#tblFiltros").change(function(){
            list();
        });
        $("#selDateDesde").change(function(){
            list();
        });
        $("#selDateHasta").change(function(){
            list();
        });
        $("#btnList").unbind("click");
        $("#btnList").click(function(){
            list();
        });
    });         
    
</script>