<?php
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui.custom.min.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery.maskedinput-1.2.2.min.js');

$this->headLink()->appendStylesheet($this->baseUrl() . '/css/table.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/alert.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/form.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/pagination.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui/jquery-ui.custom.css');

//$this->SwapBytes_Jquery->endLine(true);
?>
<meta charset="utf-8">
<h2><?php echo $this->escape($this->title); ?></h2>
<br>
<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px 0px 0px 10px; margin-left:auto; margin-right:auto;">
    <tr>
        <td align="center">
            <div id="informacion">
    
    <table id="tblusuario" align="center" >
            
        <tr>
            <td>
                    <p id="solicitud_usuario">Solicitud :</p>
            </td>
            <td>
                    <p id="s_usuariotxt"></p>
            </td>
        </tr>
        
            <tr>
                <td>
                    <p id="nombre_usuario">CI :</p>
                </td>
                <td>
                    <p id="c_usuariotxt"></p>
                </td>
            </tr>
            <tr>
                <td>
                    <p id="nombre_usuario">Nombre :</p>
                </td>
                <td>
                    <p id="n_usuariotxt"></p>
                </td>
            </tr>
             <tr>
                <td>
                    <p id="apellido_usuario">Apellido :</p>
                </td>
                <td>
                    <p id="a_usuariotxt"></p>
                </td>
            </tr>
             <tr>
                <td>
                    <p id="grupo_usuario">Perfil :</p>
                </td>
                <td>
                    <p id="g_usuariotxt"></p>
                </td>
            </tr>
        </table> 
            </div>    
        </td> 
    </tr>
    <tr>
        <td align="center"> 
          
            <?php include_once('filtros.phtml'); ?>
            
        </td>
    </tr>
    
    <tr>
        <td>
            <div id="tableData">&nbsp;</div>
        </td>
    </tr>
</table>

<?php echo $this->SwapBytes_Crud_Form->getHtml(); ?>

<script type='text/javascript'>
    $(document).ready(function(){
<?php
    echo $this->SwapBytes_Jquery->getLoading('loading');
    echo $this->SwapBytes_Ajax->getUrlAjaxJS();
    echo $this->SwapBytes_Crud_Form->getJavaScript();
    echo $this->SwapBytes_Crud_Action->getJavaScript('tableData');
//    echo $this->filters->getJavaScript('tableData', $this->SwapBytes_Jquery_Ui_Form->buttonDisable('btnAdd', true));
?>
         $.getJSON(urlAjax+"informacion/", function(data){executeCmdsFromJSON(data)})
         $.getJSON(urlAjax+"listar/", function(data){executeCmdsFromJSON(data)})
         $.getJSON(urlAjax+"Agregar/", function(data){executeCmdsFromJSON(data)})
         
         $('#btnReturn').click(function (){
           $.getJSON(urlAjax+"regreso/", function(data){executeCmdsFromJSON(data)}) 
        });
   
         
    });
    
    function myretornar(id){
         $.getJSON(urlAjax+"retornar/id/"+ id, function(data){executeCmdsFromJSON(data)});
    } 
    
    
</script>