<?php
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui.custom.min.js');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/table.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/alert.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/form.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui/jquery-ui.custom.css');

?>
<h2><?php echo $this->escape($this->title); ?></h2>
<br>
<table border="0" cellpadding="0" cellspacing="0" style="padding: 0 0 0 10; margin-left:auto; margin-right:auto;">
    <tr>
        <td align="center" style="position: relative;max-width: 300px;">
            <?php include_once('filtros.phtml'); ?>
        </td>
        <td>
            <span id='montoTotal' style='background: antiquewhite;padding: 17px;border-radius: 4px;font-size: 13px;position: relative;font-weight: bold;'>Haga clic en listar</span>
        </td>
    </tr>
</table>
<br>
<div id="tableData" align="center"></div>
<div id="undertable" style="font-size: 16px;"></div>
<?php echo $this->SwapBytes_Crud_Form->getHtml(); ?>
<script type='text/javascript'>
    $(document).ready(function(){
        <?php
        echo $this->SwapBytes_Jquery->getLoading('loading');
        echo $this->SwapBytes_Ajax->getUrlAjaxJS();
        echo $this->SwapBytes_Crud_Form->getJavaScript();
        echo $this->SwapBytes_Crud_Action->getJavaScript('tableData');
        echo $this->filters->getJavaScript('tableData');
        echo $this->trigger;
        ?>

        $("#btnList").click(function(){
            $('#btnImp').attr('disabled','')
        });

        $('#btnImp').click(function (){
                window.location.href = urlAjax + "descargar/fechas='"+$("#FechasNominas").val()+"'";
        });

        $.getJSON(urlAjax + "filter", function(data){
            executeCmdsFromJSON(data);
        });

    });

    function listado(){
        window.location.href = urlAjax + "imprimir/pk/" + id;
    }


</script>