<?php
    $this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui.custom.min.js');
    $this->headScript()->appendFile($this->baseUrl() . '/js/jquery.maskedinput-1.2.2.min.js');
    $this->headScript()->appendFile($this->baseUrl() . '/js/validator.js');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/table.css');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/alert.css');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/form.css');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/validator.css');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui/jquery-ui.custom.css');
    //$this->SwapBytes_Jquery->endLine(true);
?>
<meta charset="utf-8">
<h2><?php echo $this->escape($this->title); ?></h2>
<br>
<style>
    #contact label{
        display: inline-block;
        width: 100px;
        text-align: right;
    }
    #contact_submit{
        padding-left: 100px;
    }
    #contact div{
        margin-top: 1em;
    }
    textarea{
        vertical-align: top;
        height: 5em;
    }
    .error{
        display: none;
        margin-left: 10px;
    }      
    .error_show{
        color: red;
        margin-left: 10px;
    }
    div.ui-dialog{
        top: 50%;
        left: 37%;
    }
    #frmModal #nombre {
        width: 340px;
    }
    #frmModal #direccion {
        width: 340px;
        min-width: 340px;
        max-width: 340px;
    }
</style> 
<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px 0px 0px 10px; margin-left:auto; margin-right:auto;">
    <tr>
        <td align="center">
            <?php include_once('filtros.phtml'); ?>
        </td>
    </tr>
    <tr>
        <td>
            <div id="tableData">&nbsp;</div>
        </td>
    </tr>
</table>
<?php echo $this->SwapBytes_Crud_Form->getHtml(); ?>
<script type='text/javascript'>
    var objectToValidations =   [   
                                    {input: "nombre",       type:   "alphabetic",   fn: function(){}},
                                    {input: "direccion",    type:   "empty",        fn: function(){}},
                                    {input: "telefono",     type:   "phone",        fn: function(){}},
                                    {input: "telefono2",    type:   "phone",        fn: function(){}},
                                    {input: "rif",          type:   "numeric",      fn: function(){}}
                                ];
    //llamamos al validator 
    validator.insertValidation(objectToValidations);
    $(document).ready(function(){
        <?php
            echo $this->SwapBytes_Jquery->getLoading('loading');
            echo $this->SwapBytes_Ajax->getUrlAjaxJS();
            echo $this->SwapBytes_Crud_Form->getJavaScript();
            echo $this->SwapBytes_Crud_Action->getJavaScript('tableData');
        ?>
        //AJAX Consulta RIF
        $("body").delegate("#rif","change",function(){
            if($("#rif").val().length > 4){
                var rif = false;
                var variable = $("#rif").val();
                var tipo = $("#tipo_rif").val();
                $.ajax({
                    url: urlAjax + "getRif",
                    data: {"rif":variable, "tipo_rif":tipo},
                    dataType: "json",
                    async: true,
                    success: function(data) {
                        if(data[0]){
                           rif = true;
                        }else {
                           rif = false; 
                           $("#razonsocial").val("");            
                        }
                        if(rif){
                            $("#razonsocial").val(data[2]);
                        }
                        else {
                        }
                    },
                });
            }
        });
    });
</script>