
<?php
    $this->headScript()->appendFile($this->baseUrl() . '/js/jquery.maskedinput-1.2.2.min.js');
    $this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui.custom.min.js');
    $this->headScript()->appendFile($this->baseUrl() . '/js/angular.min.js');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/alert.css');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/form.css');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/table.css');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui/jquery-ui.custom.css');

?>
<style>

</style>

<h2 id="title" style="margin:10px ">
<?php  echo $this->title; ?>    
</h2>
<div>
    <div id="busqueda" align="center">
        <table id="tblbusqueda"  align="center">
            <tr>
                <td class='relative'>
                <?php  include_once('filtros.phtml'); ?>

                <span></span>

                </td>   
           </tr>
                    
        </table> 
    </div> 
</div>
<div id="tableData" align="center" style="margin: 0px auto;"></div>  




<script type="text/javascript">
         
    <?php
    echo $this->SwapBytes_Jquery->getLoading('loading');
    echo $this->SwapBytes_Ajax->getUrlAjaxJS();

    echo $this->SwapBytes_Crud_Action->getJavaScript('tableData');
    echo $this->filters->getJavaScript('tableData');

    $json[]="$('#selEscuela').removeAttr('disabled');";
    ?>

</script>