<?php
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui.custom.min.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery.maskedinput-1.2.2.min.js');

$this->headLink()->appendStylesheet($this->baseUrl() . '/css/table.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/alert.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/form.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui/jquery-ui.custom.css');

//$this->SwapBytes_Jquery->endLine(true);
?>
<h2><?php echo $this->escape($this->title); ?></h2>
<br>
<table border="0" cellpadding="0" cellspacing="0" width="1000px" style="padding: 0 0 0 10; margin-left:auto; margin-right:auto;">
    <tr>
        <td align="center">

            <?php include_once('filtros.phtml'); ?>
        </td>
    </tr>
</table>
<br>
<div id="tableData" align="center"></div>
<?php echo $this->SwapBytes_Crud_Form->getHtml(); ?>
<script type='text/javascript'>
    $(document).ready(function(){
<?php
echo $this->SwapBytes_Jquery->getLoading('loading');
echo $this->SwapBytes_Ajax->getUrlAjaxJS();
echo $this->SwapBytes_Crud_Form->getJavaScript();
echo $this->SwapBytes_Crud_Action->getJavaScript('tableData');
//	echo $this->filters->getJavaScript('tableData');
?>
        $.getJSON(urlAjax + "filter", function(data){executeCmdsFromJSON(data)});
    });
    
    function startTinyMCE(){
    
    };

    function startFileUploader(exts){
        
        var uploader = new qq.FileUploader({
            multiple: false,
            element: document.getElementById('file-uploader'),
            allowedExtensions: exts,
            action: '<?= $this->baseUrl() ?>/transactions/recaudos/upload/',
            debug: true,
            onSubmit: function(id, fileName){ 
                nelement = $('ul.qq-upload-list').children().length;
                if(nelement == 1){
                    alert('Solo puede subir un(1) archivo a la vez');
                    return false;
                }
            },
            onComplete: function(id, fileName, responseJSON){
                $("#recaudo").val(responseJSON.ruta);
            }
        });
    };
</script>
<style>
    .qq-upload-button{position: absolute !important; margin-top:50px !important;}
    .qq-upload-list{float:right !important; margin-top:25px !important;}
    #frmModal {height:100px !important;}
    </style>