<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  </head>
  <body>
      <h1>Ayuda</h1>
      Para realizar busquedas:
      Puede escribir dentro de la caja de texto el valor a buscar, el cual podra
      coincidir con el contenido de todas o algunas columnas que se muestran en
      la lista, si desea buscar un valor en varias columnas debe utilizar el signo
      +, y si quiere buscar un valor exacto debe encerrarlo entre comillas simples ''.
  </body>
</html>
