<?php
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui.custom.min.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery.maskedinput-1.2.2.min.js');

$this->headLink()->appendStylesheet($this->baseUrl() . '/css/table.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/alert.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/form.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui/jquery-ui.custom.css');

//$this->SwapBytes_Jquery->endLine(true);
?>
<h2><?php echo $this->escape($this->title); ?></h2>
<br>
<table border="0" cellpadding="0" cellspacing="0" width="1000px" style="padding: 0 0 0 10; margin-left:auto; margin-right:auto;">
    <tr>
        <td align="center">
            <div id="info"><?php echo $this->info; ?></div>
           <?php include_once('filtros.phtml'); ?>
        </td>
    </tr>
</table>
<br>
<div id="tableData" align="center"></div>
<?php echo $this->SwapBytes_Crud_Form->getHtml(); ?>
<script type='text/javascript'>
    $(document).ready(function(){
<?php
    echo $this->SwapBytes_Jquery->getLoading('loading');
    echo $this->SwapBytes_Ajax->getUrlAjaxJS();
    echo $this->SwapBytes_Crud_Form->getJavaScript();
    echo $this->SwapBytes_Crud_Action->getJavaScript('tableData');
    echo $this->filters->getJavaScript('tableData');
    echo $this->trigger;
?>


        $('#btnReturn').click(function (){
           $.getJSON(urlAjax+"regreso/", function(data){executeCmdsFromJSON(data)})
        });

        $("input[name=titulo]").live("change",function(){
            var titulo = $("input[name=titulo]:checked").val();
             if (titulo == 't')   {
              //alert('es titulo ');

              $.getJSON(urlAjax + "hide", function(data){executeCmdsFromJSON(data)});

              return true;
             }
             else{
              //alert('no es titutlo');

              $.getJSON(urlAjax + "hide/show/" + "true", function(data){executeCmdsFromJSON(data)});

              return false;
             }
            });

    });

    function documentos(id){

    
    $.getJSON(urlAjax + "documentos/pk/" + id, function(data){executeCmdsFromJSON(data)});
    }
</script>