<?php

$this->headScript()->appendFile($this->baseUrl() . '/js/jquery.maskedinput-1.2.2.min.js');

$this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui.custom.min.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery.md5.js');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/table.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/alert.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/form.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/pagination.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui/jquery-ui.custom.css');


//$this->SwapBytes_Jquery->endLine(true);
?>
<meta charset="utf-8">
<h2><?php echo $this->escape($this->title); ?></h2>
<br>
<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px 0px 0px 10px; margin-left:auto; margin-right:auto;">
    <tr>
        <td align="center">

            <?php include_once('filtros.phtml'); ?> 
        </td>
    </tr>
    <tr>
        <td>
            <div id="tableData">&nbsp;</div>
        </td>
    </tr>
</table>

<?php echo $this->SwapBytes_Crud_Form->getHtml(); ?>

<script type='text/javascript'>
    $(document).ready(function(){

<?php
    echo $this->SwapBytes_Jquery->getLoading('loading');
    echo $this->SwapBytes_Ajax->getUrlAjaxJS();
    echo $this->SwapBytes_Crud_Form->getJavaScript();
    echo $this->SwapBytes_Crud_Action->getJavaScript('tableData');
    echo $this->filters->getJavaScript('tableData', $this->SwapBytes_Jquery_Ui_Form->buttonDisable('btnAdd', true));
    echo $this->SwapBytes_Jquery->fillSelect('selEstado', 'estado');
    $function = $this->SwapBytes_Jquery->getJSON('cambiar', null, array('data' => $this->SwapBytes_Jquery->serializeForm()));
?>

        $.getJSON(urlAjax + "filter", function(data){executeCmdsFromJSON(data)});



   
    });

    var nav4 = window.Event ? true : false;

    function acceptNum(evt){

        // NOTE: Backspace = 8, Enter = 13, '0' = 48, '9' = 57

        var key = nav4 ? evt.which : evt.keyCode;

        return (key <= 13 || (key >= 48 && key <= 57));

    }
    
    function validar(){
        MyurlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;
       var calificacion = '';  
        $('.TextBoxNormal').each(function(e,b){
                   
              calificacion = calificacion+ b.id +"="+ b.value+"&";
        })
        
        $.getJSON(MyurlAjax + '/addoreditload/cod/'+encodeURIComponent(calificacion),function(data){executeCmdsFromJSON(data)});
        
    }

    function mencion(cod){
        MyurlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;

        var id = '#mencion' + cod;
        
        $.getJSON(MyurlAjax + '/mencion/cod/'+cod + '/mencion/' + $(id).val(),function(data){executeCmdsFromJSON(data)});
        
    }   

    function imprimir() {
        MyurlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;

        window.location.href = escape(MyurlAjax + '/imprimir/periodo/'+$('#Periodo').val() + '/sede/' + $('#Sede').val() + '/escuela/' + $('#Escuela').val());
    }
</script>