<?php

$this->headScript()->appendFile($this->baseUrl() . '/js/jquery.maskedinput-1.2.2.min.js');

$this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui.custom.min.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery.md5.js');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/table.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/alert.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/form.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/pagination.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui/jquery-ui.custom.css');


//$this->SwapBytes_Jquery->endLine(true);
?>
<meta charset="utf-8">
<h2><?php echo $this->escape($this->title); ?></h2>
<br>
<table border="0" cellpadding="0" cellspacing="0" style="padding: 0px 0px 0px 10px; margin-left:auto; margin-right:auto;">
    <tr>
        <td align="center">

            <?php include_once('filtros.phtml'); ?> 
        </td>
    </tr>
    <tr>
        <td>
            <div id="tableData">&nbsp;</div>
        </td>
    </tr>
</table>

<?php echo $this->SwapBytes_Crud_Form->getHtml(); ?>

<script type='text/javascript'>
    $(document).ready(function(){
    urlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;
    
<?php
    echo $this->SwapBytes_Jquery->getLoading('loading');
    echo $this->SwapBytes_Ajax->getUrlAjaxJS();
    echo $this->SwapBytes_Crud_Form->getJavaScript();
    echo $this->SwapBytes_Crud_Action->getJavaScript('tableData'); 
    echo $this->filters->getJavaScript('tableData', $this->SwapBytes_Jquery_Ui_Form->buttonDisable('btnAdd', true));
?>
    });
      
    function ver_tesis(cod){
        MyurlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;
        $.getJSON(MyurlAjax + '/view/id/1/cod/'+cod,function(data){executeCmdsFromJSON(data)});
    }
    
    function agregar_tesis(){
        MyurlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;
        $.getJSON(MyurlAjax + '/addoreditloadtesis/id/1',function(data){executeCmdsFromJSON(data)});
    }
    
    function editar_tesis(cod){
        MyurlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;
        $.getJSON(MyurlAjax + '/addoreditloadtesis/id/2/cod/' + cod,function(data){executeCmdsFromJSON(data)});
    }
    
    function confirm_tesis(mod){
        MyurlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;

        var value = $('#titulo').val();
        var titulo = '';

         

        $.each(value, function ( index, val ) {
            titulo = titulo + val.replace("%","[!*!]");
        });


        $.getJSON(MyurlAjax + '/addoreditconfirmtesis/mod/'+mod+'/id/'+$('#pk_datotesis').val()+'/linea/' + $('#fk_lineainvestigacion').val() + '/tema/' + $('#fk_tema').val() + '/titulo/' + titulo,function(data){executeCmdsFromJSON(data)});
         
    }

    
    
    function agregar_otrotesista(){
        MyurlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;
        $.getJSON(MyurlAjax + '/addoreditloadotrotesista',function(data){executeCmdsFromJSON(data)});
    }

    function ver_otrotesista(cod){
        MyurlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;
        $.getJSON(MyurlAjax + '/view/id/2/cod/'+cod,function(data){executeCmdsFromJSON(data)});
    }
    
    
    
    function agregar_tutor(){
        MyurlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;
        $.getJSON(MyurlAjax + '/addoreditloadtutor/id/1',function(data){executeCmdsFromJSON(data)});
    }
    
    function editar_tutor(cod,pk){
        MyurlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;
        $.getJSON(MyurlAjax + '/addoreditloadtutor/id/2/cod/' + cod + '/pk/' + pk,function(data){executeCmdsFromJSON(data)});
    }   
    
    function ver_tutor(cod,pk){
        MyurlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;
        $.getJSON(MyurlAjax + '/view/id/3/cod/'+cod+'/pk/'+pk,function(data){executeCmdsFromJSON(data)});
    }
    
    
    function renunciar(){
        MyurlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;
        $.getJSON(MyurlAjax + '/renunciatetista',function(data){executeCmdsFromJSON(data)});
        
    }

    function renuncia_tema(cod){
        MyurlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;
        $.getJSON(MyurlAjax + '/renunciatema/cod/' + cod,function(data){executeCmdsFromJSON(data)});
        
    } 
    
    function cambiar_tutor(cod,id){
        MyurlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;
        $.getJSON(MyurlAjax + '/renunciatutor/cod/'+cod+'/id/'+id,function(data){executeCmdsFromJSON(data)});
        
    }

  

    function delete_tutor(){
         MyurlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;
         $.getJSON(MyurlAjax + '/deletetutor/cod/' + $('#pk_tutortesis').val(),function(data){executeCmdsFromJSON(data)});   
    }        


    function renuncia_confirm(cod,id,tutor){
        MyurlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;
        $.getJSON(MyurlAjax + "/renunciaresponse/mod/" + cod+"/id/"+id+"/tutor/"+tutor,function(data){
            executeCmdsFromJSON(data);
            $.getJSON(MyurlAjax + '/list', function(data){executeCmdsFromJSON(data)});
        });  
    }

    function renunciatema_confirm (){
        MyurlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;
        $.getJSON(MyurlAjax + '/renunciatemaresponse/cod/' + $('#renuncia #id').val(),function(data){executeCmdsFromJSON(data)});
    }

    function planilla(){
        MyurlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;
        $.getJSON(MyurlAjax + '/planilla',function(data){executeCmdsFromJSON(data)});
    }   

    function imprimir_planilla(){
        MyurlAjax = <?php echo "'".$_SERVER['REQUEST_URI']."'";?>;
        window.location.href = escape(MyurlAjax + "/imprimir/id/" + $('#pk_datotesis').val()+ '/mod/' + $('#fase').val());
    }              

</script>