<?php
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui/jquery-ui.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui/jquery-ui.custom.css');
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui.custom.min.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery.maskedinput-1.2.2.min.js');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/table.css');
?>
<h2>
<?php  echo $this->title; ?>    
</h2>
<div align="center">
    <table  id="tblFiltro" align="center">
        <tr>
            <td>
            <?php include_once('filtros.phtml'); ?>
            </td>   
       </tr>    
    </table>
    <div>
        <div>
            <p class="title">Inscritos Regulares y Nuevos Ingresos Masculino</p>
            <table id="tableMasculino" class="tableData" align="center"></table>
        </div>
        <div>
            <p class="title">Inscritos Regulares y Nuevos Ingresos Femenino</p>
            <table id="tableFemenino" class="tableData" align="center"></table>
        </div>
    </div>
</div>
<style type="text/css">
    .title{
        padding: 5px;
        font-size: 120%;
        font-weight: bold;
        text-align: center;
        margin-bottom: 10px;
    }
    .tableData tr td, #tblTotal tr td{
        padding: 10px 5px;
    }
    .tableData tr:last-child, #tblTotal tr:last-child{
        font-weight: bold;
        font-size: 120%;
        text-align: center;
    }
    .tableData tr:last-child:hover, #tblTotal tr:last-child:hover{
        background: #ffffc5;
    }
    .tableData tr:last-child td:hover, #tblTotal tr:last-child td:hover{
        background: #ffffa5;
    }
    .tableData, #tblTotal{
        margin-bottom: 25px;
    }
</style>

<script type="text/javascript">
    <?php
        echo $this->SwapBytes_Jquery->getLoading('loading');
        echo $this->SwapBytes_Ajax->getUrlAjaxJS();
        echo $this->SwapBytes_Crud_Action->getJavaScript('tableMasculino');
        echo $this->filters->getJavaScript('tableMasculino');
        echo $this->SwapBytes_Crud_Action->getJavaScript('tableFemenino');
        echo $this->filters->getJavaScript('tableFemenino');
    ?>
    $(document).ready(function(){
        $("td[style=text-align:right;font-weight:bolder;]").hide();
        function list(){
            $.getJSON(urlAjax + "generar/filters/"+escape($('#tblFiltros').find(':input').serialize())+"", function(d){executeCmdsFromJSON(d)}); 
        };
        $("#selSede").change(function(){
            list();
        });
        $("#selPeriodo").change(function(){
            list();
        });
        var first_time = true;
        $("#selSede").ajaxStop(function(){
            if(first_time){
                list();
            }
            first_time = false;
         });
    });
</script>
