<?php
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui/jquery-ui.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/jquery-ui/jquery-ui.custom.css');
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui.custom.min.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/jquery.maskedinput-1.2.2.min.js');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/table.css');
?>
<h2>
<?php  echo $this->title; ?>    
</h2>

<div align="center">
    <table  id="tblFiltro" align="center">
        <tr>
            <td>
            <?php include_once('filtros.phtml'); ?>
            </td>   
       </tr>    
    </table> 

    <table  id="tblCantidad" class="tableData" align="center">
    </table> 
</div>
    


<style type="text/css">
    #tblCantidad{
       margin-top: 5%;
    }
    #tblCantidad tr td{
    padding: 10px 5px;
    }

 

 

    #tblCantidad td:hover{
        background: #ffffa5;

    }
    #tblFiltros{
      display: none;
    }
</style>



<script type="text/javascript">
    <?php
        echo $this->SwapBytes_Jquery->getLoading('loading');
        echo $this->SwapBytes_Ajax->getUrlAjaxJS();
        echo $this->SwapBytes_Crud_Action->getJavaScript('tblCantidad');
        echo $this->filters->getJavaScript('tblCantidad');
    ?>
    $(document).ready(function(){
        $("td[style=text-align:right;font-weight:bolder;]").hide();
        function list(){
            $.getJSON(urlAjax + "generar"+escape($('#tblFiltros').serialize())+"", function(d){executeCmdsFromJSON(d)}); 
        };
       
      list();
    });
</script>
